name: Node.js Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and start the application
        run: npm start

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SECRET_KEY }}
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USER_NAME }}
          script: |
            cd NFTrace/index.json 
            git pull
            npm install --production
            pm2 restart app.js
            pm2 start npm -- start
            
